set(command "/usr/local/lib/python2.7/dist-packages/cmake/data/bin/cmake;-P;/content/root_src/root_build/XROOTD-prefix/src/XROOTD-stamp/download-XROOTD.cmake")

execute_process(COMMAND ${command} RESULT_VARIABLE result)
if(result)
  set(msg "Command failed (${result}):\n")
  foreach(arg IN LISTS command)
    set(msg "${msg} '${arg}'")
  endforeach()
  message(FATAL_ERROR "${msg}")
endif()
set(command "/usr/local/lib/python2.7/dist-packages/cmake/data/bin/cmake;-P;/content/root_src/root_build/XROOTD-prefix/src/XROOTD-stamp/verify-XROOTD.cmake")

execute_process(COMMAND ${command} RESULT_VARIABLE result)
if(result)
  set(msg "Command failed (${result}):\n")
  foreach(arg IN LISTS command)
    set(msg "${msg} '${arg}'")
  endforeach()
  message(FATAL_ERROR "${msg}")
endif()
set(command "/usr/local/lib/python2.7/dist-packages/cmake/data/bin/cmake;-P;/content/root_src/root_build/XROOTD-prefix/src/XROOTD-stamp/extract-XROOTD.cmake")

execute_process(COMMAND ${command} RESULT_VARIABLE result)
if(result)
  set(msg "Command failed (${result}):\n")
  foreach(arg IN LISTS command)
    set(msg "${msg} '${arg}'")
  endforeach()
  message(FATAL_ERROR "${msg}")
endif()
